name = "cloudflare-accel"
main = "_worker.js"
compatibility_date = "2024-09-01"

# Optional: define variables here for local dev only.
# Do NOT commit secrets. Prefer configuring in the Cloudflare dashboard.
# [vars]
# GITHUB_PAT = ""
# GH_USERNAME = ""

# Uncomment to bind to a custom route/zone after deploying to a domain
# routes = [
#   { pattern = "accel.example.com/*", zone_name = "example.com" }
# ]
